/**
 * Single source of truth for supported schools and their residence halls.
 * Import from here anywhere school/dorm data is needed.
 *
 * Adding a new school:
 * 1. Add an entry below with name, shortName, dorms[], and optional location + logoSlug.
 * 2. Add logo image to public/brand/school-logos/{logoSlug}.png (e.g. Dayton.png).
 * 3. Booking schedule, signup, admin bookings, and calendar all read from this config.
 */

export type School = {
  name: string;
  shortName: string;
  dorms: string[];
  /** Optional: used for logo path /brand/school-logos/{logoSlug}.png. Defaults to shortName. */
  logoSlug?: string;
  /** Optional: shown on homepage under school name (e.g. "Easton, MA"). */
  location?: string;
  /** Move-out pickup window for this school (YYYY-MM-DD, inclusive). Students can only select dates within this range. */
  moveOutWindow?: { start: string; end: string };
};

export const SCHOOLS: School[] = [
  {
    name: 'Stonehill College',
    shortName: 'Stonehill',
    location: 'Easton, MA',
    logoSlug: 'Stonehill',
    moveOutWindow: { start: '2026-05-04', end: '2026-05-09' },
    dorms: [
      'Bogan Hall',
      'Boland Hall',
      'Commonwealth Courts',
      'Corr Hall',
      'Holy Cross Center',
      'Notre Dame du Lac Hall',
      "O'Hara Hall",
      "O'Hara Village",
      'Pilgrim Heights',
      'Pilgrim Heights Village — Colonial Courts',
      'Villa Theresa Hall',
      'Off-Campus Housing',
    ],
  },
  {
    name: 'University of New Haven',
    shortName: 'UNH',
    location: 'West Haven, CT',
    logoSlug: 'UNH',
    moveOutWindow: { start: '2026-05-06', end: '2026-05-13' },
    dorms: [
      'Bergami Hall',
      'Bethel Hall',
      'Bixler Hall',
      'Gerber Hall',
      'Westside Hall',
      'Celentano Hall',
      'Dunham Hall',
      'Sheffield Hall',
      'Winchester Hall',
      'The Atwood',
      'Campbell Houses',
      'Forest Hills Apartments',
      'Park View',
      'Ricardo Street House',
      'Ruden Street Apartments',
      'Off-Campus Housing',
    ],
  },
  // New schools — paste dorm lists when ready; replace placeholder with real dorms
  {
    name: 'University of Dayton',
    shortName: 'Dayton',
    location: 'Dayton, OH',
    logoSlug: 'Dayton',
    moveOutWindow: { start: '2026-05-04', end: '2026-05-09' },
    dorms: [
      'Marianist Hall',
      'Marycrest Complex',
      'Stuart Complex',
      'Virginia W. Kettering Hall',
      'Garden Apartments',
      'Campus South Apartments',
      'Student Neighborhood',
      'Caldwell Apartments',
      'ArtStreet Apartments',
      'Plumwood Apartments',
      'University Place',
      '819 Irving Avenue Apartments',
      'Adele Center Apartments',
      'Lawnview Apartments',
      'East Stewart Garden Apartments - North',
      'North Neighborhood',
      'South Neighborhood',
      'College Park Neighborhood',
      'South Student Neighborhood',
      'Sorority Houses',
    ],
  },
  {
    name: 'University of Massachusetts',
    shortName: 'UMass',
    location: 'Massachusetts',
    logoSlug: 'UMass-Amherst',
    moveOutWindow: { start: '2026-05-08', end: '2026-05-16' },
    dorms: [
      'Baker Hall (Central)',
      'Birch Hall (Commonwealth Honors College)',
      'Brett Hall (Central)',
      'Brooks Hall (Central)',
      'Brown Hall (Sylvan)',
      'Butterfield Hall (Central)',
      'Cance Hall (Southwest)',
      'Cashin Hall (Sylvan)',
      'Chadbourne Hall (Central)',
      'Coolidge Hall (Southwest)',
      'Crabtree Hall (Northeast)',
      'Crampton Hall (Southwest)',
      'Dickinson House (Orchard Hill)',
      'Dwight Hall (Northeast)',
      'Elm Hall (Commonwealth Honors College)',
      'Emerson Hall (Southwest)',
      'Field Hall (Orchard Hill)',
      'Gorman Hall (Central)',
      'Grayson Hall (Orchard Hill)',
      'Greenough Hall (Central)',
      'Hamlin Hall (Northeast)',
      'James Hall (Southwest)',
      'John Adams Hall (Southwest)',
      'John Quincy Adams Hall (Southwest)',
      'Johnson Hall (Northeast)',
      'Kennedy Hall (Southwest)',
      'Knowlton Hall (Northeast)',
      'Leach Hall (Northeast)',
      'Lewis Hall (Northeast)',
      'Linden Hall (Commonwealth Honors College)',
      'MacKimmie Hall (Southwest)',
      'Maple Hall (Commonwealth Honors College)',
      'Mary Lyon Hall (Northeast)',
      'McNamara Hall (Sylvan)',
      'Melville Hall (Southwest)',
      'Moore Hall (Southwest)',
      'North Apartment A (North)',
      'North Apartment B (North)',
      'North Apartment C (North)',
      'North Apartment D (North)',
      'Oak Hall (Commonwealth Honors College)',
      'Patterson Hall (Southwest)',
      'Pierpont Hall (Southwest)',
      'Prince Hall (Southwest)',
      'Sycamore Hall (Commonwealth Honors College)',
      'Thatcher Hall (Northeast)',
      'Thoreau Hall (Southwest)',
      'Van Meter Hall (Central)',
      'Washington Hall (Southwest)',
      'Webster Hall (Orchard Hill)',
      'Wheeler Hall (Central)',
    ],
  },
  {
    name: 'Brevard College',
    shortName: 'Brevard',
    location: 'Brevard, NC',
    logoSlug: 'Brevard',
    moveOutWindow: { start: '2026-05-01', end: '2026-05-07' },
    dorms: [
      'Beam Residence Hall',
      'Jones Hall',
      'Stanback Hall',
      'The Villages',
      'North Village',
      'Center Village',
      'South Village',
    ],
  },
  {
    name: 'Gordon College',
    shortName: 'Gordon',
    location: 'Wenham, MA',
    logoSlug: 'Gordon',
    moveOutWindow: { start: '2026-05-08', end: '2026-05-14' },
    dorms: [
      'Nyland Hall',
      'Fulton Hall',
      'Tavilla Hall',
      'Chase Hall',
      'Wilson Hall',
      'Evans Hall',
      'Ferrin Hall',
      'Bromley Hall',
      'Grace Hall',
      'Hilton Hall',
      'MacInnis Hall',
      'Conrad Hall',
      'Rider Hall',
      'Shields House',
    ],
  },
  {
    name: 'Central Connecticut State University',
    shortName: 'CCSU',
    location: 'New Britain, CT',
    logoSlug: 'CCSU',
    moveOutWindow: { start: '2026-05-11', end: '2026-05-18' },
    dorms: [
      'Mildred Barrows Hall',
      'Catharine Beecher Hall',
      'F. Don James Hall',
      'Seth North Hall',
      'Thomas Gallaudet Hall',
      'Mid-Campus Hall',
      'Robert Sheridan Hall',
      'Robert Vance Hall',
      'Sam May Hall',
      'Carroll Hall',
      'Off-Campus Housing',
    ],
  },
  {
    name: 'Sacred Heart University',
    shortName: 'SHU',
    location: 'Fairfield, CT',
    logoSlug: 'SHU',
    moveOutWindow: { start: '2026-04-28', end: '2026-05-05' },
    dorms: [
      'Elizabeth Ann Seton Hall',
      'Thomas Merton Hall',
      'Angelo Roncalli Hall',
      'Toussaint Hall',
      'Mother Teresa Hall',
      'Catherine of Siena Hall & Michael McGivney Hall',
      'Scholars Commons',
      'Augustine Hall',
      'Thomas Aquinas Hall',
      'Teresa of Avila Hall',
      'John Henry Newman Hall',
      'Christian Witness Commons',
      'Jean Donovan Hall',
      'Oscar Romero Hall',
      'Dorothy Day Hall',
      'Elie Wiesel Hall & Pier Giorgio Frassati Hall',
      'Frances Xavier Cabrini Hall',
      'Thea Bowman Hall',
      'Jorge Bergoglio Hall',
      'Oakwood Gardens',
      'The Ridge Townhouses & Apartments',
      'Pioneer Gardens Apartments',
      'Off-Campus Housing',
    ],
  },
  {
    name: 'Towson University',
    shortName: 'Towson',
    location: 'Towson, MD',
    logoSlug: 'Towson',
    moveOutWindow: { start: '2026-05-12', end: '2026-05-20' },
    dorms: [
      'Barton House',
      'Douglass House',
      'Harris Hall',
      'Tubman House',
      'Barnes Hall',
      'Marshall Hall',
      'Towson Run',
      'Millennium Hall',
      'Glen Complex',
      'Tower A',
      'Tower B',
      'Tower C',
      'Tower D',
      'Newell Hall',
      'Richmond Hall',
      'Prettyman Hall',
      'Scarborough Hall',
      'Residence Tower',
      '10 West',
      'Off-Campus Housing',
    ],
  },
  {
    name: 'University of Notre Dame',
    shortName: 'Notre Dame',
    location: 'Notre Dame, IN',
    logoSlug: 'Notre-Dame',
    moveOutWindow: { start: '2026-04-30', end: '2026-05-08' },
    dorms: [
      'Alumni Hall',
      'Baumer Hall',
      'Carroll Hall',
      'Coyle Community in Zahm Hall',
      'Dillon Hall',
      'Duncan Hall',
      'Dunne Hall',
      'Graham Family Hall',
      'Keenan Hall',
      'Keough Hall',
      'Knott Hall',
      'Morrissey Hall',
      "O'Neill Family Hall",
      'Siegfried Hall',
      'Sorin Hall',
      'Stanford Hall',
      "St. Edward's Hall",
      'Badin Hall',
      'Breen-Phillips Hall',
      'Cavanaugh Hall',
      'Farley Hall',
      'Flaherty Hall',
      'Howard Hall',
      'Johnson Family Hall',
      'Lewis Hall',
      'Lyons Hall',
      'McGlinn Hall',
      'Pasquerilla East Hall',
      'Pasquerilla West Hall',
      'Ryan Hall',
      'Walsh Hall',
      'Welsh Family Hall',
      'Off-Campus Housing',
    ],
  },
  {
    name: 'James Madison University',
    shortName: 'JMU',
    location: 'Harrisonburg, VA',
    logoSlug: 'JMU',
    moveOutWindow: { start: '2026-05-06', end: '2026-05-16' },
    dorms: [
      'Alger Hall',
      'Apartments on Grace',
      'Ashby Hall',
      'Bell Hall',
      'Chesapeake Hall',
      'Chappelear Hall',
      'Chandler Hall',
      'Cedar',
      'Converse Hall',
      'Dingledine Hall',
      'Dogwood',
      'Eagle Hall',
      'Frederikson Hall',
      'Garber Hall',
      'Gifford Hall',
      'Greek Row',
      'Hanson Hall',
      'Hillside Hall',
      'Hoffman Hall',
      'Huffman Hall',
      'Logan Hall',
      'Magnolia',
      'McGraw-Long Hall',
      'Oak',
      'Paul Jennings Hall',
      'Potomac Hall',
      'Shenandoah Hall',
      'Shorts Hall',
      'Spotswood Hall',
      'Wampler Hall',
      'Wayland Hall',
      'Weaver Hall',
      'White Hall',
      'Willow',
      'Off-Campus Housing',
    ],
  },
  {
    name: 'Bridgewater State University',
    shortName: 'Bridgewater',
    location: 'Bridgewater, MA',
    logoSlug: 'Bridgewater',
    moveOutWindow: { start: '2026-05-04', end: '2026-05-12' },
    dorms: [
      'Miles Hall',
      'DiNardo Hall',
      'Crimson Hall',
      'Stonehouse Hall',
      'Weygand Hall',
      'Scott Hall',
      'Woodward Hall',
      'Pope Hall',
      'Shea Hall',
      'Durgin Hall',
      'Great Hill Student Apartments',
      'Off-Campus Housing',
    ],
  },
];

/** Map of school name → dorm list for quick lookup */
export const SCHOOL_DORMS: Record<string, string[]> = Object.fromEntries(
  SCHOOLS.map((s) => [s.name, s.dorms])
);

/** Just the school names for dropdowns */
export const SCHOOL_NAMES: string[] = SCHOOLS.map((s) => s.name);

/** Get dorms for a given school name */
export function getDormsForSchool(schoolName: string): string[] {
  return SCHOOL_DORMS[schoolName] ?? [];
}

/** Get the move-out pickup window for a given school name, or null if not set */
export function getMoveOutWindow(schoolName: string): { start: Date; end: Date } | null {
  const school = SCHOOLS.find((s) => s.name === schoolName);
  if (!school?.moveOutWindow) return null;
  const start = new Date(school.moveOutWindow.start + 'T00:00:00');
  const end = new Date(school.moveOutWindow.end + 'T00:00:00');
  return { start, end };
}
